FROM python:3.11-slim

WORKDIR /app

# Install system dependencies, mongodump, and tzdata
RUN apt-get update && apt-get install -y wget tzdata && \
    wget -q https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian12-x86_64-100.9.3.tgz && \
    tar -xzf mongodb-database-tools-debian12-x86_64-100.9.3.tgz && \
    mv mongodb-database-tools-debian12-x86_64-100.9.3/bin/mongodump /usr/local/bin/ && \
    rm -rf mongodb-database-tools-debian12-x86_64-100.9.3* && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Keep the container running for development
CMD ["tail", "-f", "/dev/null"]
