export enum EnvKeyEnum {
    // Basic
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    SERVER_PORT = 'SERVER_PORT',
    HOST = 'HOST',
    CLIENT_URL = 'CLIENT_URL',
    MONGODB_URL = 'MONGODB_URL',
    DOTENV_OVERRIDE = 'DOTENV_OVERRIDE',

    // Redis
    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_USERNAME = 'REDIS_USERNAME',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_DB = 'REDIS_DB',

    // VNStock
    VNSTOCK_API_URL = 'VNSTOCK_API_URL',

    // Scheduled Tasks
    CLEAN_UP_KEY_TOKEN_CRON_TIME = 'CLEAN_UP_KEY_TOKEN_CRON_TIME',
    CLEAN_UP_PRODUCT_CRON_TIME = 'CLEAN_UP_PRODUCT_CRON_TIME',
    CLEAN_UP_EXPIRED_GUESTS_CRON_TIME = 'CLEAN_UP_EXPIRED_GUESTS_CRON_TIME',
    SYNC_INVENTORY_SKU_CRON_TIME = 'SYNC_INVENTORY_SKU_CRON_TIME',

    // AI
    AI_CHAT_SERVICE_URL = 'AI_CHAT_SERVICE_URL',
    GROQ_API_KEY = 'GROQ_API_KEY',
    GEMINI_API_KEY = 'GEMINI_API_KEY',

    // OAuth2 (Mail Service)
    OAUTH2_USER = 'OAUTH2_USER',
    OAUTH2_CLIENT_ID = 'OAUTH2_CLIENT_ID',
    OAUTH2_CLIENT_SECRET = 'OAUTH2_CLIENT_SECRET',
    OAUTH2_REFRESH_TOKEN = 'OAUTH2_REFRESH_TOKEN',
    OAUTH2_ACCESS_TOKEN = 'OAUTH2_ACCESS_TOKEN',

    // Google OAuth
    GOOGLE_OAUTH_CLIENT_ID = 'GOOGLE_OAUTH_CLIENT_ID',
    GOOGLE_OAUTH_CLIENT_SECRET = 'GOOGLE_OAUTH_CLIENT_SECRET',
    GOOGLE_OAUTH_REDIRECT_URI = 'GOOGLE_OAUTH_REDIRECT_URI'
}
